activity_log	CREATE TABLE `activity_log` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `user_id` int(11) NOT NULL,
 `action` varchar(50) NOT NULL,
 `entity_type` enum('room_booking','course_schedule','user') NOT NULL,
 `entity_id` int(11) DEFAULT NULL,
 `room_id` int(11) DEFAULT NULL,
 `details` text DEFAULT NULL,
 `ip_address` varchar(45) DEFAULT NULL,
 `created_at` timestamp NULL DEFAULT current_timestamp(),
 PRIMARY KEY (`id`),
 KEY `room_id` (`room_id`),
 KEY `idx_created_at` (`created_at`),
 KEY `idx_user_action` (`user_id`,`action`),
 CONSTRAINT `activity_log_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
 CONSTRAINT `activity_log_ibfk_2` FOREIGN KEY (`room_id`) REFERENCES `rooms` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=389 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci
admin_audit_log	CREATE TABLE `admin_audit_log` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `admin_id` int(11) NOT NULL,
 `action` varchar(100) NOT NULL,
 `entity_type` varchar(50) NOT NULL,
 `entity_id` int(11) DEFAULT NULL,
 `old_value` text DEFAULT NULL,
 `new_value` text DEFAULT NULL,
 `ip_address` varchar(45) DEFAULT NULL,
 `created_at` timestamp NULL DEFAULT current_timestamp(),
 PRIMARY KEY (`id`),
 KEY `admin_id` (`admin_id`),
 KEY `idx_entity` (`entity_type`,`entity_id`),
 KEY `idx_created` (`created_at`),
 CONSTRAINT `admin_audit_log_ibfk_1` FOREIGN KEY (`admin_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
booking_attempts	CREATE TABLE `booking_attempts` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `user_id` int(11) NOT NULL,
 `user_type` enum('teacher','cr') NOT NULL,
 `room_id` int(11) NOT NULL,
 `attempted_date` date NOT NULL,
 `attempted_start_time` time NOT NULL,
 `attempted_end_time` time NOT NULL,
 `purpose` varchar(200) DEFAULT NULL,
 `conflict_type` enum('room_booked','schedule_conflict') NOT NULL,
 `blocking_booking_id` int(11) DEFAULT NULL,
 `blocking_schedule_id` int(11) DEFAULT NULL,
 `is_resolved` tinyint(1) DEFAULT 0,
 `notified_at` timestamp NULL DEFAULT NULL,
 `created_at` timestamp NULL DEFAULT current_timestamp(),
 PRIMARY KEY (`id`),
 KEY `blocking_booking_id` (`blocking_booking_id`),
 KEY `blocking_schedule_id` (`blocking_schedule_id`),
 KEY `idx_unresolved` (`room_id`,`attempted_date`,`is_resolved`),
 KEY `idx_user_attempts` (`user_id`,`is_resolved`),
 KEY `idx_created` (`created_at`),
 CONSTRAINT `booking_attempts_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
 CONSTRAINT `booking_attempts_ibfk_2` FOREIGN KEY (`room_id`) REFERENCES `rooms` (`id`) ON DELETE CASCADE,
 CONSTRAINT `booking_attempts_ibfk_3` FOREIGN KEY (`blocking_booking_id`) REFERENCES `room_bookings` (`id`) ON DELETE SET NULL,
 CONSTRAINT `booking_attempts_ibfk_4` FOREIGN KEY (`blocking_schedule_id`) REFERENCES `course_schedule` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
buildings	CREATE TABLE `buildings` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `faculty_id` int(11) DEFAULT NULL,
 `name` varchar(100) NOT NULL,
 `code` varchar(10) NOT NULL,
 `description` text DEFAULT NULL,
 `status` enum('active','inactive') NOT NULL DEFAULT 'active',
 `created_at` timestamp NULL DEFAULT current_timestamp(),
 PRIMARY KEY (`id`),
 UNIQUE KEY `code` (`code`),
 KEY `idx_buildings_faculty` (`faculty_id`),
 CONSTRAINT `fk_buildings_faculty` FOREIGN KEY (`faculty_id`) REFERENCES `faculties` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci
courses	CREATE TABLE `courses` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `degree_program_id` int(11) NOT NULL,
 `department_id` int(11) DEFAULT NULL,
 `level` int(11) NOT NULL,
 `semester` int(11) NOT NULL,
 `course_code` varchar(20) NOT NULL,
 `course_name` varchar(100) NOT NULL,
 `credits` decimal(3,1) DEFAULT 0.0,
 `contact_hours` int(11) DEFAULT 0,
 `course_type` enum('compulsory','elective') DEFAULT 'compulsory',
 `status` enum('active','inactive') DEFAULT 'active',
 `created_at` timestamp NULL DEFAULT current_timestamp(),
 PRIMARY KEY (`id`),
 UNIQUE KEY `unique_course` (`degree_program_id`,`level`,`semester`,`course_code`),
 KEY `fk_courses_department` (`department_id`),
 CONSTRAINT `courses_ibfk_1` FOREIGN KEY (`degree_program_id`) REFERENCES `degree_programs` (`id`) ON DELETE CASCADE,
 CONSTRAINT `fk_courses_department` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=129 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci
course_schedule	CREATE TABLE `course_schedule` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `room_id` int(11) NOT NULL,
 `degree_program_id` int(11) DEFAULT NULL,
 `course_code` varchar(20) NOT NULL,
 `course_name` varchar(100) NOT NULL,
 `level` int(11) NOT NULL,
 `semester` int(11) NOT NULL,
 `group_name` varchar(20) DEFAULT NULL,
 `semester_id` int(11) DEFAULT NULL,
 `day_of_week` int(11) NOT NULL,
 `start_time` time NOT NULL,
 `end_time` time NOT NULL,
 `is_whole_semester` tinyint(1) DEFAULT 1,
 `start_date` date DEFAULT NULL,
 `end_date` date DEFAULT NULL,
 `status` enum('scheduled','cancelled') DEFAULT 'scheduled',
 `purpose` varchar(255) DEFAULT 'Theory Class' COMMENT 'Purpose of the scheduled class',
 `cancelled_at` timestamp NULL DEFAULT NULL,
 `cancelled_by` int(11) DEFAULT NULL,
 `cancellation_reason` varchar(200) DEFAULT NULL,
 `created_by` int(11) DEFAULT NULL,
 `created_at` timestamp NULL DEFAULT current_timestamp(),
 `teacher_id` int(11) DEFAULT NULL,
 PRIMARY KEY (`id`),
 KEY `degree_program_id` (`degree_program_id`),
 KEY `created_by` (`created_by`),
 KEY `idx_schedule_active` (`room_id`,`day_of_week`,`status`,`start_date`,`end_date`),
 KEY `fk_schedule_cancelled_by` (`cancelled_by`),
 KEY `idx_cs_semester` (`semester_id`),
 KEY `fk_schedule_teacher` (`teacher_id`),
 CONSTRAINT `course_schedule_ibfk_1` FOREIGN KEY (`room_id`) REFERENCES `rooms` (`id`) ON DELETE CASCADE,
 CONSTRAINT `course_schedule_ibfk_3` FOREIGN KEY (`degree_program_id`) REFERENCES `degree_programs` (`id`) ON DELETE SET NULL,
 CONSTRAINT `course_schedule_ibfk_4` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
 CONSTRAINT `course_schedule_ibfk_5` FOREIGN KEY (`cancelled_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
 CONSTRAINT `fk_schedule_cancelled_by` FOREIGN KEY (`cancelled_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
 CONSTRAINT `fk_schedule_teacher` FOREIGN KEY (`teacher_id`) REFERENCES `teachers` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci
degree_programs	CREATE TABLE `degree_programs` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `faculty_id` int(11) NOT NULL,
 `name` varchar(100) NOT NULL,
 `code` varchar(20) NOT NULL,
 `level_type` enum('bachelor','masters','phd') DEFAULT 'bachelor',
 `total_levels` int(11) DEFAULT 4,
 `semesters_per_level` int(11) DEFAULT 2,
 `status` enum('active','inactive') NOT NULL DEFAULT 'active',
 `created_at` timestamp NULL DEFAULT current_timestamp(),
 PRIMARY KEY (`id`),
 UNIQUE KEY `code` (`code`),
 KEY `faculty_id` (`faculty_id`),
 CONSTRAINT `degree_programs_ibfk_1` FOREIGN KEY (`faculty_id`) REFERENCES `faculties` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci
departments	CREATE TABLE `departments` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `faculty_id` int(11) NOT NULL,
 `name` varchar(100) NOT NULL,
 `code` varchar(20) NOT NULL,
 `status` enum('active','inactive') NOT NULL DEFAULT 'active',
 `created_at` timestamp NULL DEFAULT current_timestamp(),
 PRIMARY KEY (`id`),
 UNIQUE KEY `dept_code` (`code`),
 KEY `faculty_id` (`faculty_id`),
 CONSTRAINT `departments_ibfk_1` FOREIGN KEY (`faculty_id`) REFERENCES `faculties` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci
faculties	CREATE TABLE `faculties` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `name` varchar(100) NOT NULL,
 `code` varchar(20) NOT NULL,
 `status` enum('active','inactive') NOT NULL DEFAULT 'active',
 `created_at` timestamp NULL DEFAULT current_timestamp(),
 PRIMARY KEY (`id`),
 UNIQUE KEY `code` (`code`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci
floors	CREATE TABLE `floors` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `building_id` int(11) NOT NULL,
 `floor_number` int(11) NOT NULL,
 `status` enum('active','inactive') NOT NULL DEFAULT 'active',
 PRIMARY KEY (`id`),
 UNIQUE KEY `building_id` (`building_id`,`floor_number`),
 CONSTRAINT `floors_ibfk_1` FOREIGN KEY (`building_id`) REFERENCES `buildings` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci
login_attempts	CREATE TABLE `login_attempts` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `identifier` varchar(255) NOT NULL COMMENT 'username or IP',
 `ip_address` varchar(45) NOT NULL,
 `user_agent` varchar(500) DEFAULT NULL,
 `attempted_at` timestamp NULL DEFAULT current_timestamp(),
 `was_successful` tinyint(1) DEFAULT 0,
 PRIMARY KEY (`id`),
 KEY `idx_identifier_time` (`identifier`,`attempted_at`),
 KEY `idx_ip_time` (`ip_address`,`attempted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
notifications	CREATE TABLE `notifications` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `user_id` int(11) NOT NULL,
 `title` varchar(100) NOT NULL,
 `message` text NOT NULL,
 `type` enum('booking_freed','booking_created','schedule_change','system') NOT NULL,
 `related_type` enum('booking','schedule') DEFAULT NULL,
 `related_id` int(11) DEFAULT NULL,
 `is_read` tinyint(1) DEFAULT 0,
 `created_at` timestamp NULL DEFAULT current_timestamp(),
 `notify_admin` tinyint(1) DEFAULT 0,
 PRIMARY KEY (`id`),
 KEY `idx_user_unread` (`user_id`,`is_read`),
 CONSTRAINT `notifications_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci
remember_tokens	CREATE TABLE `remember_tokens` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `user_id` int(11) NOT NULL,
 `token_hash` varchar(64) NOT NULL,
 `expires_at` datetime NOT NULL,
 `created_at` timestamp NULL DEFAULT current_timestamp(),
 PRIMARY KEY (`id`),
 KEY `idx_token` (`token_hash`),
 KEY `idx_user` (`user_id`),
 KEY `idx_expires` (`expires_at`),
 CONSTRAINT `fk_remember_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
rooms	CREATE TABLE `rooms` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `floor_id` int(11) NOT NULL,
 `faculty_id` int(11) DEFAULT NULL,
 `room_number` varchar(20) NOT NULL,
 `room_name` varchar(100) NOT NULL,
 `room_type` enum('lab','theory','seminar','auditorium') NOT NULL DEFAULT 'theory',
 `capacity` int(11) DEFAULT 50,
 `has_projector` tinyint(1) DEFAULT 1,
 `has_ac` tinyint(1) DEFAULT 0,
 `description` text DEFAULT NULL,
 `created_at` timestamp NULL DEFAULT current_timestamp(),
 `status` enum('active','inactive') NOT NULL DEFAULT 'active',
 `room_number_edited` tinyint(1) NOT NULL DEFAULT 0,
 PRIMARY KEY (`id`),
 UNIQUE KEY `floor_id` (`floor_id`,`room_number`),
 KEY `faculty_id` (`faculty_id`),
 CONSTRAINT `rooms_ibfk_1` FOREIGN KEY (`floor_id`) REFERENCES `floors` (`id`) ON DELETE CASCADE,
 CONSTRAINT `rooms_ibfk_2` FOREIGN KEY (`faculty_id`) REFERENCES `faculties` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=35 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci
room_bookings	CREATE TABLE `room_bookings` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `room_id` int(11) NOT NULL,
 `booked_by` int(11) NOT NULL,
 `purpose` varchar(200) NOT NULL,
 `booking_date` date NOT NULL,
 `start_time` time NOT NULL,
 `end_time` time NOT NULL,
 `course_schedule_id` int(11) DEFAULT NULL,
 `degree_program_id` int(11) DEFAULT NULL,
 `level` int(11) DEFAULT NULL,
 `semester` int(11) DEFAULT NULL,
 `group_name` varchar(20) DEFAULT NULL,
 `status` enum('booked','cancelled') DEFAULT 'booked',
 `cancelled_at` timestamp NULL DEFAULT NULL,
 `cancelled_by` int(11) DEFAULT NULL,
 `cancellation_reason` varchar(200) DEFAULT NULL,
 `created_at` timestamp NULL DEFAULT current_timestamp(),
 `course_id` int(11) DEFAULT NULL,
 `teacher_id` int(11) DEFAULT NULL,
 PRIMARY KEY (`id`),
 KEY `booked_by` (`booked_by`),
 KEY `freed_by` (`cancelled_by`),
 KEY `course_schedule_id` (`course_schedule_id`),
 KEY `degree_program_id` (`degree_program_id`),
 KEY `idx_room_date` (`room_id`,`booking_date`,`status`),
 KEY `idx_booking_date` (`booking_date`),
 KEY `idx_booking_lookup` (`room_id`,`booking_date`,`status`,`start_time`,`end_time`),
 KEY `idx_status_time` (`status`,`booking_date`,`start_time`,`end_time`),
 KEY `fk_booking_teacher` (`teacher_id`),
 CONSTRAINT `fk_booking_teacher` FOREIGN KEY (`teacher_id`) REFERENCES `teachers` (`id`) ON DELETE SET NULL,
 CONSTRAINT `room_bookings_ibfk_1` FOREIGN KEY (`room_id`) REFERENCES `rooms` (`id`) ON DELETE CASCADE,
 CONSTRAINT `room_bookings_ibfk_2` FOREIGN KEY (`booked_by`) REFERENCES `users` (`id`) ON DELETE CASCADE,
 CONSTRAINT `room_bookings_ibfk_3` FOREIGN KEY (`cancelled_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
 CONSTRAINT `room_bookings_ibfk_4` FOREIGN KEY (`course_schedule_id`) REFERENCES `course_schedule` (`id`) ON DELETE SET NULL,
 CONSTRAINT `room_bookings_ibfk_5` FOREIGN KEY (`degree_program_id`) REFERENCES `degree_programs` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=39 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci
schedule_exceptions	CREATE TABLE `schedule_exceptions` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `course_schedule_id` int(11) NOT NULL,
 `exception_date` date NOT NULL,
 `exception_type` enum('cancelled','rescheduled') NOT NULL,
 `new_room_id` int(11) DEFAULT NULL,
 `new_start_time` time DEFAULT NULL,
 `new_end_time` time DEFAULT NULL,
 `reason` varchar(200) DEFAULT NULL,
 `created_by` int(11) NOT NULL,
 `created_at` timestamp NULL DEFAULT current_timestamp(),
 PRIMARY KEY (`id`),
 UNIQUE KEY `course_schedule_id` (`course_schedule_id`,`exception_date`),
 KEY `created_by` (`created_by`),
 KEY `new_room_id` (`new_room_id`),
 KEY `idx_exception_lookup` (`course_schedule_id`,`exception_date`),
 CONSTRAINT `schedule_exceptions_ibfk_1` FOREIGN KEY (`course_schedule_id`) REFERENCES `course_schedule` (`id`) ON DELETE CASCADE,
 CONSTRAINT `schedule_exceptions_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE CASCADE,
 CONSTRAINT `schedule_exceptions_ibfk_3` FOREIGN KEY (`new_room_id`) REFERENCES `rooms` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
semesters	CREATE TABLE `semesters` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `name` varchar(50) NOT NULL,
 `start_date` date DEFAULT NULL,
 `end_date` date DEFAULT NULL,
 `degree_program_id` int(11) DEFAULT NULL,
 `level` int(11) DEFAULT NULL,
 `semester_num` int(11) NOT NULL DEFAULT 1,
 `group_name` varchar(20) NOT NULL DEFAULT '',
 `created_by` int(11) DEFAULT NULL,
 `created_at` timestamp NULL DEFAULT current_timestamp(),
 PRIMARY KEY (`id`),
 UNIQUE KEY `uq_semester_combo` (`degree_program_id`,`level`,`semester_num`,`group_name`),
 CONSTRAINT `fk_semester_degree` FOREIGN KEY (`degree_program_id`) REFERENCES `degree_programs` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci
teachers	CREATE TABLE `teachers` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `full_name` varchar(100) NOT NULL,
 `email` varchar(100) DEFAULT NULL,
 `phone` varchar(20) DEFAULT NULL,
 `department_id` int(11) NOT NULL,
 `user_id` int(11) DEFAULT NULL COMMENT 'Links to users.id when teacher registers',
 `created_at` timestamp NULL DEFAULT current_timestamp(),
 `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
 PRIMARY KEY (`id`),
 UNIQUE KEY `email` (`email`),
 KEY `department_id` (`department_id`),
 KEY `user_id` (`user_id`),
 CONSTRAINT `teachers_ibfk_1` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`),
 CONSTRAINT `teachers_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=67 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci
time_slots	CREATE TABLE `time_slots` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `slot_name` varchar(20) NOT NULL,
 `start_time` time NOT NULL,
 `end_time` time NOT NULL,
 `slot_order` int(11) NOT NULL,
 PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci
users	CREATE TABLE `users` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `username` varchar(50) NOT NULL,
 `password` varchar(255) NOT NULL,
 `full_name` varchar(100) NOT NULL,
 `user_type` enum('super_admin','faculty_dean','teacher','cr') NOT NULL,
 `email` varchar(100) DEFAULT NULL,
 `phone` varchar(20) DEFAULT NULL,
 `teacher_id` varchar(50) DEFAULT NULL,
 `department_id` int(11) DEFAULT NULL,
 `degree_program_id` int(11) DEFAULT NULL,
 `assigned_level` int(11) DEFAULT NULL,
 `assigned_semester` int(11) DEFAULT NULL,
 `batch` varchar(20) DEFAULT NULL,
 `group_name` varchar(20) DEFAULT NULL,
 `is_active` tinyint(1) DEFAULT 1,
 `account_status` enum('pending','active','inactive') NOT NULL DEFAULT 'active',
 `created_at` timestamp NULL DEFAULT current_timestamp(),
 `faculty_id` int(11) DEFAULT NULL,
 `password_reset_token` varchar(64) DEFAULT NULL,
 `password_reset_expires` datetime DEFAULT NULL,
 `last_password_change` datetime DEFAULT NULL,
 `failed_login_count` int(11) DEFAULT 0,
 `locked_until` datetime DEFAULT NULL,
 `unlock_otp` varchar(64) DEFAULT NULL,
 `unlock_otp_expires` datetime DEFAULT NULL,
 `email_verified` tinyint(1) DEFAULT 0,
 `email_token` varchar(64) DEFAULT NULL,
 `email_token_expires` datetime DEFAULT NULL,
 PRIMARY KEY (`id`),
 UNIQUE KEY `username` (`username`),
 KEY `degree_program_id` (`degree_program_id`),
 KEY `fk_user_department` (`department_id`),
 KEY `fk_users_faculty` (`faculty_id`),
 CONSTRAINT `fk_user_department` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE SET NULL,
 CONSTRAINT `fk_users_faculty` FOREIGN KEY (`faculty_id`) REFERENCES `faculties` (`id`) ON DELETE SET NULL,
 CONSTRAINT `users_ibfk_1` FOREIGN KEY (`degree_program_id`) REFERENCES `degree_programs` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci